const books = [
    {
      id: 1,
      title: "The Great Adventure",
      description: "An epic tale of adventure and discovery.",
      coverImage: "/book1.jpg",
      author: 'John Doe',
      rating: 4, // Directly in the public folder
      content: "The wind howled through the ancient trees of the Elmswood Forest, carrying with it the scent of rain and the whispers of forgotten times. In the small village of Brayfield, nestled on the edge of the forest, a young boy named Aric was about to discover a secret that would change his life foreverAric had always felt different, an outsider in a village where everyone knew their place. His dreams were filled with visions of a distant land, a place where dragons soared through the skies and ancient towers touched the clouds. Little did he know, these dreams were not mere figments of his imagination but memories of a life he had yet to live.On the eve of his fifteenth birthday, Aric's world was turned upside down. A mysterious stranger arrived in Brayfield, bearing a message that had been hidden for centuries. The man, cloaked in shadows, spoke of a prophecy—a prophecy that foretold the rise of a hero from humble beginnings, a hero destined to save Eldoria from an ancient evil.You are the one, the stranger whispered, his eyes gleaming with the knowledge of a thousand lifetimes.The last of the Dragonborn, the blood of kings runs through your veins.Aric's heart raced as the words sank in. Could it be true? Could he, an ordinary boy from a forgotten village, be the hero of legend?As the storm clouds gathered overhead, Aric knew that his life would never be the same. The journey ahead would be fraught with danger, but he could not deny the call of destiny. He would leave behind all that he knew and venture into the unknown, seeking the answers that lay beyond the forest's edge.With the weight of the prophecy on his shoulders, Aric took his first step toward his destiny. The Chronicles of Eldoria had begun.",
    },
    {
      id: 2,
      title: "Mystery of the Lost City",
      description: "A thrilling mystery set in a forgotten city.",
      coverImage: "/book1.jpg", // Directly in the public folder
      author: 'John Doe',
      rating: 4,
      content: "The wind howled through the ancient trees of the Elmswood Forest, carrying with it the scent of rain and the whispers of forgotten times. In the small village of Brayfield, nestled on the edge of the forest, a young boy named Aric was about to discover a secret that would change his life foreverAric had always felt different, an outsider in a village where everyone knew their place. His dreams were filled with visions of a distant land, a place where dragons soared through the skies and ancient towers touched the clouds. Little did he know, these dreams were not mere figments of his imagination but memories of a life he had yet to live.On the eve of his fifteenth birthday, Aric's world was turned upside down. A mysterious stranger arrived in Brayfield, bearing a message that had been hidden for centuries. The man, cloaked in shadows, spoke of a prophecy—a prophecy that foretold the rise of a hero from humble beginnings, a hero destined to save Eldoria from an ancient evil.You are the one, the stranger whispered, his eyes gleaming with the knowledge of a thousand lifetimes.The last of the Dragonborn, the blood of kings runs through your veins.Aric's heart raced as the words sank in. Could it be true? Could he, an ordinary boy from a forgotten village, be the hero of legend?As the storm clouds gathered overhead, Aric knew that his life would never be the same. The journey ahead would be fraught with danger, but he could not deny the call of destiny. He would leave behind all that he knew and venture into the unknown, seeking the answers that lay beyond the forest's edge.With the weight of the prophecy on his shoulders, Aric took his first step toward his destiny. The Chronicles of Eldoria had begun.",
    },
    {
      id: 1,
      title: "The Great Adventure",
      description: "An epic tale of adventure and discovery.",
      coverImage: "/book1.jpg",
      author: 'John Doe',
      rating: 4, // Directly in the public folder
      content: "The wind howled through the ancient trees of the Elmswood Forest, carrying with it the scent of rain and the whispers of forgotten times. In the small village of Brayfield, nestled on the edge of the forest, a young boy named Aric was about to discover a secret that would change his life foreverAric had always felt different, an outsider in a village where everyone knew their place. His dreams were filled with visions of a distant land, a place where dragons soared through the skies and ancient towers touched the clouds. Little did he know, these dreams were not mere figments of his imagination but memories of a life he had yet to live.On the eve of his fifteenth birthday, Aric's world was turned upside down. A mysterious stranger arrived in Brayfield, bearing a message that had been hidden for centuries. The man, cloaked in shadows, spoke of a prophecy—a prophecy that foretold the rise of a hero from humble beginnings, a hero destined to save Eldoria from an ancient evil.You are the one, the stranger whispered, his eyes gleaming with the knowledge of a thousand lifetimes.The last of the Dragonborn, the blood of kings runs through your veins.Aric's heart raced as the words sank in. Could it be true? Could he, an ordinary boy from a forgotten village, be the hero of legend?As the storm clouds gathered overhead, Aric knew that his life would never be the same. The journey ahead would be fraught with danger, but he could not deny the call of destiny. He would leave behind all that he knew and venture into the unknown, seeking the answers that lay beyond the forest's edge.With the weight of the prophecy on his shoulders, Aric took his first step toward his destiny. The Chronicles of Eldoria had begun.",
    },
    {
      id: 2,
      title: "Mystery of the Lost City",
      description: "A thrilling mystery set in a forgotten city.",
      coverImage: "/book1.jpg",
      author: 'John Doe',
      rating: 4, // Directly in the public folder
      content: "The wind howled through the ancient trees of the Elmswood Forest, carrying with it the scent of rain and the whispers of forgotten times. In the small village of Brayfield, nestled on the edge of the forest, a young boy named Aric was about to discover a secret that would change his life foreverAric had always felt different, an outsider in a village where everyone knew their place. His dreams were filled with visions of a distant land, a place where dragons soared through the skies and ancient towers touched the clouds. Little did he know, these dreams were not mere figments of his imagination but memories of a life he had yet to live.On the eve of his fifteenth birthday, Aric's world was turned upside down. A mysterious stranger arrived in Brayfield, bearing a message that had been hidden for centuries. The man, cloaked in shadows, spoke of a prophecy—a prophecy that foretold the rise of a hero from humble beginnings, a hero destined to save Eldoria from an ancient evil.You are the one, the stranger whispered, his eyes gleaming with the knowledge of a thousand lifetimes.The last of the Dragonborn, the blood of kings runs through your veins.Aric's heart raced as the words sank in. Could it be true? Could he, an ordinary boy from a forgotten village, be the hero of legend?As the storm clouds gathered overhead, Aric knew that his life would never be the same. The journey ahead would be fraught with danger, but he could not deny the call of destiny. He would leave behind all that he knew and venture into the unknown, seeking the answers that lay beyond the forest's edge.With the weight of the prophecy on his shoulders, Aric took his first step toward his destiny. The Chronicles of Eldoria had begun.",},
    {
      id: 1,
      title: "The Great Adventure",
      description: "An epic tale of adventure and discovery.",
      coverImage: "/book1.jpg",
      author: 'John Doe',
      rating: 4, // Directly in the public folder
      content: "The wind howled through the ancient trees of the Elmswood Forest, carrying with it the scent of rain and the whispers of forgotten times. In the small village of Brayfield, nestled on the edge of the forest, a young boy named Aric was about to discover a secret that would change his life foreverAric had always felt different, an outsider in a village where everyone knew their place. His dreams were filled with visions of a distant land, a place where dragons soared through the skies and ancient towers touched the clouds. Little did he know, these dreams were not mere figments of his imagination but memories of a life he had yet to live.On the eve of his fifteenth birthday, Aric's world was turned upside down. A mysterious stranger arrived in Brayfield, bearing a message that had been hidden for centuries. The man, cloaked in shadows, spoke of a prophecy—a prophecy that foretold the rise of a hero from humble beginnings, a hero destined to save Eldoria from an ancient evil.You are the one, the stranger whispered, his eyes gleaming with the knowledge of a thousand lifetimes.The last of the Dragonborn, the blood of kings runs through your veins.Aric's heart raced as the words sank in. Could it be true? Could he, an ordinary boy from a forgotten village, be the hero of legend?As the storm clouds gathered overhead, Aric knew that his life would never be the same. The journey ahead would be fraught with danger, but he could not deny the call of destiny. He would leave behind all that he knew and venture into the unknown, seeking the answers that lay beyond the forest's edge.With the weight of the prophecy on his shoulders, Aric took his first step toward his destiny. The Chronicles of Eldoria had begun.",
    },
    {
      id: 2,
      title: "Mystery of the Lost City",
      description: "A thrilling mystery set in a forgotten city.",
      coverImage: "/book1.jpg",
      author: 'John Doe',
      rating: 4, // Directly in the public folder
      content: "The wind howled through the ancient trees of the Elmswood Forest, carrying with it the scent of rain and the whispers of forgotten times. In the small village of Brayfield, nestled on the edge of the forest, a young boy named Aric was about to discover a secret that would change his life foreverAric had always felt different, an outsider in a village where everyone knew their place. His dreams were filled with visions of a distant land, a place where dragons soared through the skies and ancient towers touched the clouds. Little did he know, these dreams were not mere figments of his imagination but memories of a life he had yet to live.On the eve of his fifteenth birthday, Aric's world was turned upside down. A mysterious stranger arrived in Brayfield, bearing a message that had been hidden for centuries. The man, cloaked in shadows, spoke of a prophecy—a prophecy that foretold the rise of a hero from humble beginnings, a hero destined to save Eldoria from an ancient evil.You are the one, the stranger whispered, his eyes gleaming with the knowledge of a thousand lifetimes.The last of the Dragonborn, the blood of kings runs through your veins.Aric's heart raced as the words sank in. Could it be true? Could he, an ordinary boy from a forgotten village, be the hero of legend?As the storm clouds gathered overhead, Aric knew that his life would never be the same. The journey ahead would be fraught with danger, but he could not deny the call of destiny. He would leave behind all that he knew and venture into the unknown, seeking the answers that lay beyond the forest's edge.With the weight of the prophecy on his shoulders, Aric took his first step toward his destiny. The Chronicles of Eldoria had begun.",
    },
    // Add more books as needed
  ];
  export default books;